import { SimStrategy } from "./types";

export const SIM_STRATEGIES: SimStrategy[] = [
  {
    id: "breakout",
    name: "Breakout",
    icon: "🚀",
    timeframe: "M15 / H1",
    assets: "All major pairs",
    entryTrigger: "Candle close above/below key level with volume confirmation",
    slLogic: "Below/above the breakout level or last swing",
    tpLogic: "1:2 R:R minimum, or next structure level",
    riskRule: "1% per trade, max 2 trades/session",
    orderTypes: ["Buy Stop", "Sell Stop"],
    checklist: [
      "Identify consolidation range",
      "Mark breakout level clearly",
      "Wait for candle close beyond level",
      "Confirm with volume or momentum",
      "Place SL below/above range",
    ],
    description: "Trade breakouts from consolidation zones with momentum confirmation.",
  },
  {
    id: "pullback",
    name: "Pullback / Retracement",
    icon: "🔄",
    timeframe: "M15 / H1",
    assets: "Trending pairs (GBPUSD, EURUSD)",
    entryTrigger: "Price pulls back to Fib 0.618 or moving average in trending market",
    slLogic: "Beyond the pullback extreme or Fib 0.786",
    tpLogic: "Previous swing high/low or Fib extension 1.272",
    riskRule: "1% per trade",
    orderTypes: ["Buy Limit", "Sell Limit"],
    checklist: [
      "Confirm trend direction (HH/HL or LH/LL)",
      "Wait for pullback to key level",
      "Mark Fibonacci retracement",
      "Look for rejection candle at level",
      "Set SL beyond pullback extreme",
    ],
    description: "Enter on pullbacks within an established trend using Fibonacci confluence.",
  },
  {
    id: "support-resistance",
    name: "Support & Resistance Bounce",
    icon: "🛡️",
    timeframe: "H1 / H4",
    assets: "All pairs",
    entryTrigger: "Strong rejection candle at proven S/R zone",
    slLogic: "Beyond the S/R zone with buffer",
    tpLogic: "Next S/R level or midpoint",
    riskRule: "1% per trade, min 1:1.5 R:R",
    orderTypes: ["Buy Limit", "Sell Limit", "Market"],
    checklist: [
      "Identify key S/R zones (min 2 touches)",
      "Wait for price to reach zone",
      "Look for rejection wick/pin bar",
      "Confirm with RSI divergence (optional)",
      "Place SL beyond the zone",
    ],
    description: "Trade bounces off proven support and resistance zones with confirmation.",
  },
  {
    id: "liquidity-sweep",
    name: "Liquidity Sweep",
    icon: "💧",
    timeframe: "M5 / M15",
    assets: "EURUSD, GBPUSD, XAUUSD",
    entryTrigger: "Price sweeps above/below equal highs/lows then reverses with displacement",
    slLogic: "Beyond the liquidity sweep wick",
    tpLogic: "Opposite liquidity pool or FVG fill",
    riskRule: "0.5-1% per trade",
    orderTypes: ["Market", "Limit"],
    checklist: [
      "Identify equal highs/lows (liquidity pool)",
      "Wait for sweep beyond the level",
      "Confirm with strong displacement candle",
      "Identify FVG or OB for entry refinement",
      "Set SL above/below sweep wick",
    ],
    description: "Trade reversals after smart money sweeps liquidity from retail stop losses.",
  },
  {
    id: "trend-continuation",
    name: "Trend Continuation",
    icon: "📈",
    timeframe: "M15 / H1",
    assets: "All trending pairs",
    entryTrigger: "BOS confirmed + pullback to OB/FVG in trend direction",
    slLogic: "Below last higher low (uptrend) or above last lower high (downtrend)",
    tpLogic: "Previous swing projection or Fib 1.618 extension",
    riskRule: "1% per trade, max 3 trades with trend",
    orderTypes: ["Buy Limit", "Sell Limit", "Market"],
    checklist: [
      "Confirm overall trend on HTF",
      "Identify BOS on LTF",
      "Wait for pullback to discount/premium",
      "Find OB or FVG for entry",
      "Set SL at structure invalidation",
    ],
    description: "Ride the trend by entering on structural pullbacks after break of structure.",
  },
  {
    id: "range-scalp",
    name: "Range Scalp",
    icon: "📊",
    timeframe: "M5 / M15",
    assets: "EURUSD, USDJPY during Asia session",
    entryTrigger: "Price reaches range extreme with reversal candle",
    slLogic: "Beyond range boundary + spread buffer",
    tpLogic: "Opposite range boundary or range midpoint",
    riskRule: "0.5% per trade, max 4 trades/session",
    orderTypes: ["Buy Limit", "Sell Limit"],
    checklist: [
      "Identify clear range (min 3 touches each side)",
      "Mark range high and low precisely",
      "Wait for price at range extreme",
      "Confirm with rejection candle pattern",
      "Use tight SL beyond range edge",
    ],
    description: "Scalp between range boundaries during low-volatility sessions.",
  },
  {
    id: "order-block",
    name: "Order Block Entry",
    icon: "🧱",
    timeframe: "M15 / H1",
    assets: "All major pairs, XAUUSD",
    entryTrigger: "Price returns to a valid OB after BOS, shows reaction",
    slLogic: "Beyond the OB body (not wick)",
    tpLogic: "Next OB or liquidity target",
    riskRule: "1% per trade",
    orderTypes: ["Buy Limit", "Sell Limit"],
    checklist: [
      "Identify valid OB (last opposing candle before impulse)",
      "Confirm OB caused a BOS",
      "Wait for price to return to OB zone",
      "Look for LTF confirmation at OB",
      "Set SL beyond OB with buffer",
    ],
    description: "Enter at institutional order blocks validated by break of structure.",
  },
  {
    id: "fvg-fill",
    name: "Fair Value Gap Fill",
    icon: "📐",
    timeframe: "M5 / M15",
    assets: "XAUUSD, GBPUSD, EURUSD",
    entryTrigger: "Price fills into FVG and shows rejection at consequent encroachment",
    slLogic: "Beyond the FVG boundary",
    tpLogic: "Swing high/low beyond FVG or opposing FVG",
    riskRule: "0.5-1% per trade",
    orderTypes: ["Buy Limit", "Sell Limit"],
    checklist: [
      "Identify displacement move creating FVG",
      "Mark FVG zone (3-candle pattern)",
      "Wait for price to fill to CE (50%)",
      "Confirm direction aligns with HTF bias",
      "Set SL beyond full FVG invalidation",
    ],
    description: "Trade price filling fair value gaps with entry at consequent encroachment.",
  },
  {
    id: "free-practice",
    name: "Free Practice",
    icon: "🎯",
    timeframe: "Any",
    assets: "Any",
    entryTrigger: "Your own rules — no strategy enforcement",
    slLogic: "Your choice",
    tpLogic: "Your choice",
    riskRule: "Your choice",
    orderTypes: ["Market", "Buy Limit", "Sell Limit", "Buy Stop", "Sell Stop"],
    checklist: [],
    description: "Practice freely without strategy constraints. AI coach will only observe and journal.",
  },
];
